sudo: false
env:
  global:
  - secure: J1xqFhA2jT8S5f5bpryopVj2AIA35eHlWDHHJSlyZKFQQHsnK+cUo3XoP1qatuv242WlKkaj8iBmsg9UcpZN0V5vN8wi5AM+6afeDyXjnmDr88KErfo03WCzWXtOKYNXZK4bx0pUP9McBXWq76GnefWRzD7fDUofZPm+oCylI9A=
language: python
python:
- 2.7
install:
- pip install tox
script:
- tox
